---
- hosts: all
  become: yes
  vars:
    timesync_ntp_servers:
      - hostname: 2.rhel.pool.ntp.org
        pool: yes
        iburst: yes
  roles:
    - rhel-system-roles.timesync

- hosts: all
  become: yes
  roles:
    - set_TZ

